--- #YAML:1.0
name:                Dancer-Template-Ctpp2
version:             0.01
abstract:            HTML::CTPP2 wrapper for Dancer
license:             perl
author:              
    - Maxim Nikolenko <mephist@zenon.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Dancer:                        1.175
    HTML::CTPP2:                   0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
