--- #YAML:1.0
name:               Dancer-Template-Ctpp2
version:            0.02
abstract:           HTML::CTPP2 wrapper for Dancer
author:
    - Maxim Nikolenko <mephist@zenon.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:       1.175
    HTML::CTPP2:  0
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
